site_name: skyant.data

docs_dir: .docs
repo_url: https://gitlab.com/skyant/python/data
repo_name: skyant/python/data
edit_uri: ""

theme: 
    name: material
    favicon: https://skyant.dev/assets/icons/558614-512-3.png
    logo: https://skyant.dev/assets/icons/558614.svg
    palette:
        primary: amber
        accent: deep purple
    font:
        text: Montserrat
        code: Roboto Mono
    icon:
        repo: fontawesome/brands/gitlab
    features:
        - search.highlight
        - search.suggest
        - navigation.tabs
        - navigation.tabs.sticky


copyright: Copyright &copy; 2020 Iurii Tarasenko
extra:
    generator: true
    homepage: https://skyant.dev

    social:
        
        - icon: fontawesome/solid/sack-dollar
          link: https://buymeacoffee.com/skyantdev
        
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/company/skyantdev

        - icon: fontawesome/solid/user-group
          link: https://groups.google.com/a/skyant.dev/g/community?label=data


extra_css:
    - static/css/skyant.css
    - static/css/hide-title.css


plugins:
    - mkdocstrings:
        handlers:
            python:
                options:
                    show_source: true
                    show_root_full_path: false
                    show_root_toc_entry: true
                    show_bases: false
                    show_category_heading: false
    - search:
        indexing: 'full'

    - section-index


nav:

    - 'HOME': index.md
    - 'QUICK START': start.md
    - 'ENTITY':
        - entity/index.md
        - 'CamelModel': entity/config/CamelModel.md
        - 'NoAdditional': entity/config/NoAdditional.md
        - 'FirestoreRef': entity/fields/FirestoreRef.md
        - 'Local': entity/files/Local.md
        - 'Firestore': entity/google/Firestore.md
        - 'Storage': entity/google/Storage.md
        - 'Tasks': entity/google/Tasks.md
        - 'PubSub': entity/google/PubSub.md
        - 'REST': entity/rest/General.md
    - 'DATASET':
        - dataset/index.md
    - 'TOOLS':
        - tools/index.md
        - 'json': tools/json.md
        - 'file': tools/file.md
