INHERIT: .mkdocs.global.yml

site_name: !ENV [SITE_NAME, READTHEDOCS_SITE_NAME, 'Z']
repo_url: !!python/object/apply:os.getenv ["REPO_URL"]
repo_name: !ENV REPO_NAME

nav:

    - 'HOME': index.md
    - 'QUICK START': start.md
    - 'ENTITY':
        - entity/index.md
        - 'CamelModel': entity/config/CamelModel.md
        - 'NoAdditional': entity/config/NoAdditional.md
        - 'FirestoreRef': entity/fields/FirestoreRef.md
        - 'Local': entity/files/Local.md
        - 'Firestore': entity/google/Firestore.md
        - 'Storage': entity/google/Storage.md
        - 'Tasks': entity/google/Tasks.md
        - 'PubSub': entity/google/PubSub.md
        - 'REST': entity/rest/General.md
    - 'DATASET':
        - dataset/index.md
    - 'TOOLS':
        - tools/index.md
        - 'json': tools/json.md
        - 'file': tools/file.md
