version: 2

mkdocs:
    configuration: .mkdocs.yml
    fail_on_warning: false
formats: all

build:
    os: ubuntu-22.04
    tools:
        python: "3.10"
    jobs:
        pre_build:
            -   export SITE_NAME=${SITE_NAME}
            -   export REPO_URL=${REPO_URL}
            -   export REPO_NAME=${REPO_NAME}
            -   export COMMUNITY_URL=${COMMUNITY_URL}

python:
    install:
        - requirements: .docs/readthedocs.pip

search:
    ignore:
        - 404.html
