version: 2

mkdocs:
    configuration: .mkdocs.yml
    fail_on_warning: false
formats: all

build:
    os: ubuntu-22.04
    tools:
        python: "3.10"
    jobs:
        pre_build:
          - >
            python3 <<EOF
            import yaml
            from yaml_env_tag import construct_env_tag
            yaml.Loader.add_constructor("!ENV", construct_env_tag)
            EOF

python:
    install:
        - requirements: .docs/readthedocs.pip

search:
    ignore:
        - 404.html
