nav:

    - 'HOME': index.md
    - 'ENTITY':
        - entity/index.md
        - 'LOCAL': entity/local.md
        - 'GOOGLE':
            - entity/google/index.md
            - 'FIRESTORE': entity/google/firestore.md
            - 'PUBSUB': entity/google/pubsub.md
            - 'STORAGE': entity/google/storage.md
            - 'TASKS': entity/google/tasks.md
        - 'REST': entity/rest.md
    - 'DATASET':
        - dataset/index.md
    - 'REFERENCES':
        - references/index.md
        - 'ENTITY':
            - references/entity/index.md
            - 'CamelModel': references/entity/config/CamelModel.md
            - 'NoAdditional': references/entity/config/NoAdditional.md
            - 'FirestoreRef': references/entity/fields/FirestoreRef.md
            - 'Local': references/entity/files/Local.md
            - 'Firestore': references/entity/google/Firestore.md
            - 'Storage': references/entity/google/Storage.md
            - 'Tasks': references/entity/google/Tasks.md
            - 'PubSub': references/entity/google/PubSub.md
            - 'REST': references/entity/rest/General.md
        - 'TOOLS':
            - references/tools/index.md
            - 'json': references/tools/json.md
            - 'file': references/tools/file.md
        - 'DATASET':
            - references/dataset/index.md


site_name: Pydantic for Omnicloud
repo_url: https://github.com/omnicloudworld/pydantic
repo_name: omnicloudworld/pydantic





###
#  Template
###


docs_dir: .
edit_uri: ""


extra:

    generator: true
    homepage: https://docs.omnicloud.world
    #analytics:
    #    provider: google
    #    property: G-1R41YK6WT2

    social:
        
        - icon: fontawesome/brands/square-facebook
          link: https://facebook.com/omnicloudworld
          name: facebook
        
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/company/omnicloudworld
          name: linkedin

        - icon: fontawesome/solid/house
          link: https://omnicloud.world
          name: home


theme: 
    name: material
    favicon: https://static.omnicloud.world/common/img/icons/omni-color02.png
    logo: https://static.omnicloud.world/common/img/icons/omni.drawio.png
    palette:
        primary: amber
        accent: deep purple
    font:
        text: Comfortaa
        code: Montserrat
    icon:
        repo: fontawesome/brands/github
    features:
        - search.highlight
        - search.suggest
        - navigation.tabs
        - content.code.annotate
        - content.tabs.link


extra_css:
    - https://static.omnicloud.world/common/css/mkdocs/main.css
    - https://static.omnicloud.world/common/css/mkdocs/hide-title.css
    #- https://static.omnicloud.world/common/css/mkdocs/hide-versions.css
    - https://static.omnicloud.world/common/css/mkdocs/big-versions.css


plugins:
    - mkdocstrings:
        handlers:
            python:
                options:
                    show_source: true
                    show_root_full_path: false
                    show_root_toc_entry: false
                    show_bases: false
                    show_category_heading: false
    - search
    - section-index
    - glightbox
    - include-markdown
    - same-dir


markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - admonition
    - pymdownx.details
    - footnotes
    - attr_list
    - pymdownx.tabbed:
        alternate_style: true 
    - md_in_html
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true
